name: Pytest-PeopleWork
on:
  push:
    branches:
      - feature # Branch name

jobs:
  checks-bat-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
          pip install faker

      - name: Test with pytest
        run:
          pytest -vs
