name: Pytest-PeopleWork
on:
  push:
    branches:
      - feature # Branch name

jobs:
  checks-bat-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip && pip install pytest && pip install selenium && pip install faker && pip install openpyxl


      - name: Test with pytest
        run:
          cd /d D://
          pytest -vs
